# Generated by Django 5.2.16 on 2026-07-22 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('prompt', models.CharField(max_length=48)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Awaiting processing'), ('accepted', 'Accepted for processing'), ('rejected', 'Requires manual processing')], default='waiting', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.PositiveSmallIntegerField()),
                ('sentence_count', models.PositiveSmallIntegerField()),
                ('avg_sentence_length', models.DecimalField(decimal_places=1, max_digits=3)),
                ('lexical_diversity', models.DecimalField(decimal_places=1, max_digits=3)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_confidence', models.DecimalField(decimal_places=3, max_digits=4)),
                ('character_error_rate', models.DecimalField(decimal_places=3, max_digits=4)),
                ('word_error_rate', models.DecimalField(decimal_places=3, max_digits=4)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('composition', models.DecimalField(decimal_places=1, max_digits=3)),
                ('grammar', models.DecimalField(decimal_places=1, max_digits=3)),
                ('vocabulary', models.DecimalField(decimal_places=1, max_digits=3)),
                ('spelling', models.DecimalField(decimal_places=1, max_digits=3)),
                ('comprehension', models.DecimalField(decimal_places=1, max_digits=3)),
                ('holistic', models.DecimalField(decimal_places=1, max_digits=3)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HW', 'Handwritten'), ('SP', 'Spoken'), ('TY', 'Typed')], default='TY', max_length=2)),
                ('file', models.FileField(upload_to='submissions/')),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
    ]
