# Generated by Django 5.2.17 on 2026-09-27 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=48)),
                ('prompt', models.CharField(max_length=48)),
                ('text', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('waiting', 'Essay has not been evaluated as yet'), ('pass', 'Routed to transformer for scoring'), ('fail', 'Routed to human scorer for manual processing'), ('scored', 'Essay has been evaluated and assigned trait scores')], default='waiting', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=48)),
                ('prompt', models.CharField(max_length=48)),
                ('file', models.FileField(upload_to='./assets/audio_files')),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_count', models.PositiveSmallIntegerField()),
                ('sentence_count', models.PositiveSmallIntegerField()),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_logprob', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('compression_ratio', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.PositiveSmallIntegerField()),
                ('organization', models.PositiveSmallIntegerField()),
                ('word_choice', models.PositiveSmallIntegerField()),
                ('sentence_fluency', models.PositiveSmallIntegerField()),
                ('conventions', models.PositiveSmallIntegerField()),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.essay')),
            ],
        ),
    ]
