# Generated by Django 5.2.17 on 2026-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='uploaded_as',
            field=models.CharField(default='Text', max_length=6),
        ),
    ]
