# Generated by Django 5.2.17 on 2026-09-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_essay_uploaded_as'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essay',
            name='status',
        ),
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
